= Homework on Solution Strategies for a ThermoElectric Model
:toc: left
:author: Christophe Prud'homme
:stem: latemath

We consider the thermo-electric Model described in
http://book.feelpp.org/toolbox/thermoelectric/ and the associated
testcase from LNCMI.

== Installation

First you need to install the files on Atlas on your account
execute the following commands on Atlas. 

[source,shell]
----
# define GITHUB_USER_LOGIN in your shell environment
export GITHUB_USER_LOGIN=<your github login>

# execute script to install the 
bash -c $(curl -L https://raw.githubusercontent.com/feelpp/csmi-scientific-computing-2/master/install.sh) cs ${GITHUB_USER_LOGIN}
----

It will

* create a directory `/ssd/${USER}/feel/cs/`
* clone your git repository in `csmi-scientific-computing-2-${GITHUB_USER_LOGIN}`
* copy the data files (Feel++ mesh and config  files) required for the homework in the directory `/ssd/${USER}/feel/cs/HL-31_H1`


== Homework

We are interested in finding what is the best strategy and have a
comparison between the strategies in terms of timing and number of
iterations when varying the following parameters:

* Mesh size, you have three different meshes sizes (`-coarse`,
`-medium`, `-fine`)
* Polynomial order, you have two polymmial orders : 1 and 2
* Number of processors, you have access to Atlas cluster up to 96 cores.

In order to achieve this study, you will need to use the Atlas Cluster,
a script `cs.slurm` is provided to be able to execute the code on Atlas
using Slurm as a job sheduler. _Hint:_ you will have to use `sbatch` to
submit the jobs.

=== Job scheduling study

You will

* study and explain what the script does;
* explain how to change the script and possibly the Feel++ configuration
file in order to run the study proposed hereafter.

You will use this documentation http://book.feelpp.org/clusters/atlas/
and this one https://gitlab.math.unistra.fr/atlas/cluster-doc/wikis/home
as well as any other documentation you may find to explain. The
explanations should not take much more than one page.

=== Preconditioner study

Use the range of preconditioners (`jacobi`, `bjacobi`, `sor`,
`ilu`, `icc`, `asm`, `gasm`, `gamg`).

* Provide a brief description for each preconditioner. 
* Try to elaborate some explanations regarding the performances of your strategies and relate them to the
expected theoretival behavior of these strategies.
* For the best strategy, provide a speedup study.

A complete list of preconditioner is available
herefootnote:[http://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/PC/PCType.html]
)seen in the course to do that.

== Report

You write the report in asciidoc and upload it to the github repository assigned to you.
Use the table features of asciidoc, see eg link:http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#tables[asciidoc  documentation].
Do not forget that the report should be generated properly with the link:http://asciidoctor.org/news/2013/09/18/introducing-asciidoctor-js-live-preview/[ascidoctor-js plugin] installed on your browser(chrome or firefox). That is how I will be able to review your work.
